FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD target/com.eizzy.recharge.rest.jar app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8080,suspend=n"
EXPOSE 8080 8080
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -jar /app.jar" ]